### PR TITLE
Conditional Slots

### PR DESCRIPTION
**Pull request by tanhauhau**
[rendered](https://github.com/sveltejs/rfcs/blob/c7d708cc9c1ee925f474c29e0ee8d3a8c3ab648d/text/0000-conditional-slots.md)

Related issues: 
- https://github.com/sveltejs/svelte/issues/5604
- https://github.com/sveltejs/svelte/issues/6059
- https://github.com/sveltejs/svelte/issues/7651

### CODE REVIEW

**Comment by techniq** [comment]
@tanhauhau Sounds like this might be able to handle [$$slots with slot forwarding](https://github.com/sveltejs/svelte/issues/6059)?

**Comment by tanhauhau** [comment]
> @tanhauhau Sounds like this might be able to handle [$$slots with slot forwarding](https://github.com/sveltejs/svelte/issues/6059)?

@techniq yea, so you would write:

```svelte
<Field>
   {#if $$slots.label}
	<slot name="label" slot="label" />
   {/if}
   {#if $$slots.description}
	<slot name="description" slot="description" />
   {/if}
</Field>
```

**Comment by brandonmcconnell** [comment]
I would also very much like to see this added to resolve the same issue mentioned above, a rather common issue when working with slots in Svelte: [$$slots with slot forwarding](https://github.com/sveltejs/svelte/issues/6059)

**Comment by TristanBrotherton** [comment]
I am very much in need of this as forwarded slots as currently implemented is pretty broken with no work-around for checking of content. See: https://svelte.dev/repl/1757f88780b644519bb30c2b68b10873?version=3.55.1

**Comment by risalfajar** [comment]
Any reason this hasn't been merged yet?
I also need this.

**Comment by dummdidumm** [comment]
Conditional slots will be possible in Svelte 5 through snippets and render tags. Whether or not we want to add syntax sugar with if+snippet inside remains to be seen. Closing this RFC - thank you.

**Comment by brandonmcconnell** [comment]
@dummdidumm @tanhauhau

Outside of Svelte 5, this PR introduces a valuable and foundational solution to slot forwarding across both methodologies — with and without runes — simply by using `{#if}`.

Could we merge this in addition to the other very welcome solutions?

Thanks!

**Comment by opensas** [comment]
I stumbled upon this issue trying to conditionally forward a named slot (meaning, if the slot has not been specified, I don't want to pass any slot at all, instead of passing an empty slot and missing the fallback)

I think conditional slots are really needed in svelte 4 to address issues like this:
- https://github.com/sveltejs/svelte/issues/5604#issuecomment-2005449376
- https://github.com/sveltejs/svelte/issues/6059

I there a reason why this PR has been closed? or was it only meant fr svelte 5?

or perhaps it has it been declined in favor of this one: https://github.com/sveltejs/svelte/pull/8304

**Pull request closed without merging**
