### PR TITLE
Better slots and component composition.

### PR DESCRIPTION
**Pull request by TheComputerM**
[Rendered](https://github.com/TheComputerM/rfcs/blob/thecomputerm/slots/text/0000-better-slots.md)

This is my first RFC so please comment any helpful suggestions.

### CODE REVIEW

**Comment by TheComputerM** [comment]
Somewhat like https://github.com/sveltejs/svelte/pull/4556

**Comment by lukeed** [comment]
I was just going to link that – what are the differences? It looks like this is implemented as described

**Comment by TheComputerM** [comment]
This is still incomplete and I am brain storming on better syntax.
The goal of it is to provide a more svelte like syntax and some additional features also such as slot options:
```html
<Component>
  <svelte:fragment dense={true}>
    This will do something in the component
  </svelte:fragment>
</Component>
```

**Comment by lukeed** [comment]
Wouldn't slots just be a portal for _where_ to render? The contents of _what_ is rendered is determined by the content itself.

As far as I understand it, this RFC seems to be mostly about using `svelte:fragment` to render text nodes (non-component and non-element) with siblings.

I have an RFC open about inheriting `<slot/>` attributes (#15)
But (imo) if you're passing `dense={true}` so that the slot can react/alter its display, then I think that falls more into `svelte:template` territory (#34).

But, I might be misunderstanding you completely. I'm sorta guessing at the examples

**Comment by TheComputerM** [comment]
Yeah, sorry for the short explanation. Was thinking more on the lines of something like this:
The syntax is just for better understanding.
```html
<svelte:slot tag={ListItem} export:dense on:click={func}>
  Default
</svelte:slot>
```

```html
<svelte:fragment dense={true}>
  Content
</svelte:fragment>
```

```html
<ListItem dense={true} on:click={func}>
  Content
</ListItem>
```

**Comment by TheComputerM** [comment]
This was mainly intended to solve https://github.com/sveltejs/svelte/issues/2079 and add some new features.

**Comment by lukeed** [comment]
No problem

Yeah, to me that's 100% an inline component, if not an external component. Either of which only get _placed_ by a `<slot>`

**Pull request closed without merging**
